Document new connection callback API and `useConnection` hook.
xyflow/web pull request #472
Opened 2024-08-19 22:18 UTC by hayleigh-dot-dev

We tweaked the types of `useConnection`, `onConnectEnd`, and `onReconnectEnd` slightly. This PR updates the docs to reflect the new API. It also documents the `InternalNode` type as that was being referenced without being documented.

Closes #471.

2024-08-20 08:53 UTC, moklick requested changes

2024-08-20 08:53 UTC, moklick commented on sites/reactflow.dev/src/page-data/reference/ReactFlow.props.ts
> +      type: '(event: React.MouseEvent, edge: Edge, handleType: "source" | "target", connectionState: Omit<ConnectionState, \'inProgress\'>) => void',
We created a new type `LastConnectionType` for this. Could you use it here and for `onConnectEnd` too?

2024-08-27 08:04 UTC, hayleigh-dot-dev commented on sites/reactflow.dev/src/page-data/reference/ReactFlow.props.ts
> +      type: '(event: React.MouseEvent, edge: Edge, handleType: "source" | "target", connectionState: Omit<ConnectionState, \'inProgress\'>) => void',
I can't find a reference to a `LastConnectionType` in the codebase? Both `onConnectEnd` and `onReconnectEnd` use `connectionState: FinalConnectionState` where `FinalConnectionState` is a type alias for the type documented above.

See: https://github.com/xyflow/xyflow/blob/7b8fe28b37f79dd80ed0f915b834f2f61c57b73e/packages/system/src/types/general.ts#L53 and https://github.com/xyflow/xyflow/blob/7b8fe28b37f79dd80ed0f915b834f2f61c57b73e/packages/system/src/xyhandle/types.ts#L37

---

I can make a page for `FinalConnectionState` but it felt a little superfluous to have a separate page for a type identical to `ConnectionState` save for one field. Your call.

2024-08-28 22:07 UTC, moklick commented on sites/reactflow.dev/src/page-data/reference/ReactFlow.props.ts
> +      type: '(event: React.MouseEvent, edge: Edge, handleType: "source" | "target", connectionState: Omit<ConnectionState, \'inProgress\'>) => void',
yep, that make sense. If some one asks, we can still add it.

2024-08-28 22:07 UTC, merged

2024-08-28 22:07 UTC, moklick commented
Good idea to document `InternalNode` as well!